os:
  - 'linux'
sudo: false
language: python
python:
  - '3.8'
  - '3.9'
install:
  - pip install -r ./requirements/ci.txt
  - pip install .
script:
  - py.test --verbose ./il2fb/regiments ./tests --cov ./il2fb/regiments ./tests
after_success:
  - codecov
notifications:
  email: false
